#!/bin/sh

set -e

pxe_server_ip=$(ifconfig $INTERFACE | grep 'inet addr:' | cut -d: -f2 | awk '{print $1}')

echo Server IP: $pxe_server_ip

# Update pxelinux config to point real server ip
sed -i -e s/%\(server_ip\)s/$pxe_server_ip/ /var/lib/tftpboot/pxelinux.cfg/*

/bin/bash
